# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 603)
        mainWindow.setMouseTracking(False)
        mainWindow.setAutoFillBackground(False)

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # Botones
        self.pushButtonExcelCreator = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExcelCreator.setGeometry(QtCore.QRect(280, 520, 121, 41))
        self.pushButtonExcelCreator.setObjectName("pushButtonExcelCreator")

        self.pushButtonPDFCreator = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPDFCreator.setGeometry(QtCore.QRect(410, 520, 111, 41))
        self.pushButtonPDFCreator.setObjectName("pushButtonPDFCreator")

        self.pushButtonAddWork = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddWork.setGeometry(QtCore.QRect(550, 470, 161, 31))
        self.pushButtonAddWork.setObjectName("pushButtonAddWork")

        self.pushButtonDeleteWork = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteWork.setGeometry(QtCore.QRect(150, 470, 191, 31))
        self.pushButtonDeleteWork.setObjectName("pushButtonDeleteWork")


        # Entradas de Tiempo
        self.dateTimeEditInit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEditInit.setGeometry(QtCore.QRect(580, 410, 194, 22))
        self.dateTimeEditInit.setObjectName("dateTimeEditInit")

        self.dateTimeEditEnd = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEditEnd.setGeometry(QtCore.QRect(580, 440, 194, 22))
        self.dateTimeEditEnd.setObjectName("dateTimeEditEnd")


        # Entrada de Nombre del Equipo
        self.lineEditNameID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNameID.setGeometry(QtCore.QRect(590, 350, 181, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lineEditNameID.setFont(font)
        self.lineEditNameID.setObjectName("lineEditNameID")


        # Combo Box para mostrar opciones
        self.comboBoxColaborators = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxColaborators.setGeometry(QtCore.QRect(138, 90, 311, 22))
        self.comboBoxColaborators.setObjectName("comboBoxColaborators")

        self.comboBoxCoordinations = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCoordinations.setGeometry(QtCore.QRect(598, 90, 181, 22))
        self.comboBoxCoordinations.setObjectName("comboBoxCoordinations")

        self.comboBoxEquipments = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxEquipments.setGeometry(QtCore.QRect(590, 320, 181, 22))
        self.comboBoxEquipments.setObjectName("comboBoxEquipments")

        self.comboBoxSubstations = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSubstations.setGeometry(QtCore.QRect(590, 380, 181, 22))
        self.comboBoxSubstations.setObjectName("comboBoxSubstations")


        # Tabla para ver los trabajos ingresados al sistema
        self.tableViewWorks = QtWidgets.QTableView(self.centralwidget)
        self.tableViewWorks.setGeometry(QtCore.QRect(30, 320, 421, 141))
        self.tableViewWorks.setObjectName("tableViewWorks")

        # Listas para ver datos del colaborador y coordinacion
        self.listViewColaborator = QtWidgets.QListView(self.centralwidget)
        self.listViewColaborator.setGeometry(QtCore.QRect(30, 120, 421, 141))
        self.listViewColaborator.setObjectName("listViewColaborator")

        self.listViewCoordination = QtWidgets.QListView(self.centralwidget)
        self.listViewCoordination.setGeometry(QtCore.QRect(490, 120, 291, 141))
        self.listViewCoordination.setObjectName("listViewCoordination")

        # Nombres de Cada Parte
        self.label_equipment = QtWidgets.QLabel(self.centralwidget)
        self.label_equipment.setGeometry(QtCore.QRect(490, 320, 55, 16))
        self.label_equipment.setObjectName("label_equipment")
        self.label_inithour = QtWidgets.QLabel(self.centralwidget)
        self.label_inithour.setGeometry(QtCore.QRect(490, 410, 91, 16))
        self.label_inithour.setObjectName("label_inithour")
        self.label_endhour = QtWidgets.QLabel(self.centralwidget)
        self.label_endhour.setGeometry(QtCore.QRect(490, 440, 91, 16))
        self.label_endhour.setObjectName("label_endhour")
        self.label_place = QtWidgets.QLabel(self.centralwidget)
        self.label_place.setGeometry(QtCore.QRect(490, 380, 55, 16))
        self.label_place.setObjectName("label_place")
        self.label_equipment_id = QtWidgets.QLabel(self.centralwidget)
        self.label_equipment_id.setGeometry(QtCore.QRect(490, 350, 91, 16))
        self.label_equipment_id.setObjectName("label_equipment_id")
        self.label_colaborator = QtWidgets.QLabel(self.centralwidget)
        self.label_colaborator.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_colaborator.setObjectName("label_colaborator")
        self.label_coordination = QtWidgets.QLabel(self.centralwidget)
        self.label_coordination.setGeometry(QtCore.QRect(490, 90, 101, 16))
        self.label_coordination.setObjectName("label_coordination")

        # Titulos de cada seccion
        self.label_mainTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_mainTitle.setGeometry(QtCore.QRect(240, 10, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_mainTitle.setFont(font)
        self.label_mainTitle.setObjectName("label_mainTitle")
        self.labelTitleColaborator = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleColaborator.setGeometry(QtCore.QRect(130, 60, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleColaborator.setFont(font)
        self.labelTitleColaborator.setObjectName("labelTitleColaborator")
        self.labelTitleCoordination = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleCoordination.setGeometry(QtCore.QRect(510, 60, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleCoordination.setFont(font)
        self.labelTitleCoordination.setObjectName("labelTitleCoordination")
        self.labelTitleWorks = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleWorks.setGeometry(QtCore.QRect(50, 290, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleWorks.setFont(font)
        self.labelTitleWorks.setObjectName("labelTitleWorks")
        self.labelTitleNewWork = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleNewWork.setGeometry(QtCore.QRect(540, 290, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleNewWork.setFont(font)
        self.labelTitleNewWork.setObjectName("labelTitleNewWork")

        # Lineas para Dividir
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 270, 781, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 500, 781, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(450, 40, 41, 451))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 30, 781, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")


        # Barra de menu superior
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")

        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")

        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")

        mainWindow.setStatusBar(self.statusbar)
        self.actionGenerador_de_Planillas = QtWidgets.QAction(mainWindow)
        self.actionGenerador_de_Planillas.setObjectName("actionGenerador_de_Planillas")
        
        self.actionCreador_del_Programa = QtWidgets.QAction(mainWindow)
        self.actionCreador_del_Programa.setObjectName("actionCreador_del_Programa")
        
        self.actionVersi_n = QtWidgets.QAction(mainWindow)
        self.actionVersi_n.setObjectName("actionVersi_n")
        
        self.menuAcerca_de.addSeparator()
        self.menuAcerca_de.addAction(self.actionGenerador_de_Planillas)
        self.menuAcerca_de.addAction(self.actionCreador_del_Programa)
        self.menuAcerca_de.addAction(self.actionVersi_n)
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Generador de Planillas - Dirección de Operaciones y Mantenimiento"))
        self.pushButtonExcelCreator.setText(_translate("mainWindow", "Generar Excel"))
        self.pushButtonPDFCreator.setText(_translate("mainWindow", "Generar PDF"))
        self.label_equipment.setText(_translate("mainWindow", "Equipo:"))
        self.label_inithour.setText(_translate("mainWindow", "Hora Inicial:"))
        self.label_endhour.setText(_translate("mainWindow", "Hora Final:"))
        self.label_place.setText(_translate("mainWindow", "Lugar:"))
        self.label_equipment_id.setText(_translate("mainWindow", "ID del Equipo:"))
        self.pushButtonAddWork.setText(_translate("mainWindow", "Añadir Trabajo Realizado"))
        self.pushButtonDeleteWork.setText(_translate("mainWindow", "Eliminar Trabajo Seleccionado"))
        self.label_colaborator.setText(_translate("mainWindow", "Colaborador:"))
        self.label_coordination.setText(_translate("mainWindow", "Coordinación:"))
        self.label_mainTitle.setText(_translate("mainWindow", "GENERADOR DE PLANILLAS - DOM - ETESA"))
        self.labelTitleColaborator.setText(_translate("mainWindow", "DATOS DEL COLABORADOR"))
        self.labelTitleCoordination.setText(_translate("mainWindow", "DATOS DE LA COORDINACIÓN"))
        self.labelTitleWorks.setText(_translate("mainWindow", "TRABAJOS REALIZADOS EN LA QUINCENA ACTUAL"))
        self.labelTitleNewWork.setText(_translate("mainWindow", "AÑADIR NUEVO TRABAJO"))
        self.menuAcerca_de.setTitle(_translate("mainWindow", "Acerca de"))
        self.actionGenerador_de_Planillas.setText(_translate("mainWindow", "Generador de Planillas"))
        self.actionCreador_del_Programa.setText(_translate("mainWindow", "Creador del Programa"))
        self.actionVersi_n.setText(_translate("mainWindow", "Versión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
